services:
  h-ui:
    image: jonssonyan/h-ui:latest
    container_name: h-ui
    restart: always
    ports:
      - "443:443/udp"
      - "443:443/tcp"
      - "80:80"
      - "8081:8081"
    volumes:
      - ./h-ui-data:/h-ui/data
      - ./certbot/conf:/etc/letsencrypt:ro
    environment:
      - TZ=Europe/Moscow
    command: >
      ./h-ui
      -p 8081
      --cert /etc/letsencrypt/live/hystori.neoproxy.online/fullchain.pem
      --key /etc/letsencrypt/live/hystori.neoproxy.online/privkey.pem

networks:
  default:
    driver: bridge
